// Generated by CoffeeScript 1.6.2
(function() {
  define(['underscore', 'd3Logic'], function(_, d3Logic) {
    return [
      '$scope', '$http', '$routeParams', 'notificationService', 'accountService', 'machineService', 'metricService', 'sharedProperties', function($scope, $http, $routeParams, notify, accountService, machineService, metricService, sharedProperties) {
        $scope.welcomeMessage = 'Red Hat PhD Admin';
        $scope.denormMachines = [];
        sharedProperties.handleRouteParams($routeParams);
        $scope.sharedProperties = sharedProperties;
        $scope.getD3MetricValues = function(machine, metricName, beginDate, endDate) {
          return metricService.getMetricValues(machine.accountId, machine.orgId, machine.uuid, metricName, beginDate, endDate, function(data) {
            return console.log("Received: " + data);
          });
        };
        $scope.$watch("groupAccountBy", function(newVal) {
          return d3Logic.accountToTree({
            accountId: $scope.sharedProperties.accountId,
            data: $scope.sharedProperties.accountData,
            groupBy: newVal
          }, function(result) {
            return $scope.sharedProperties.accountTree = result;
          });
        });
        $scope.$apply();
      }
    ];
  });

}).call(this);
