// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    return [
      '$scope', '$http', 'notificationService', 'accountService', 'machineService', function($scope, $http, notify, accountService, machineService) {
        $scope.welcomeMessage = 'Red Hat PhD Admin';
        $scope.accounts = [];
        $scope.accountMachines = [];
        $scope.createTestData = function(accountId) {
          return accountService.createTestData(accountId, function(data) {
            return notify.success("Successfully created test using accountId: " + accountId);
          });
        };
        $scope.deleteTestData = function(accountId) {
          return accountService.deleteTestData(accountId, function(data) {
            return notify.success("Successfully deleted test data associated with account id: " + accountId);
          });
        };
        $scope.refreshAccounts = function() {
          return accountService.getAccounts(function(data) {
            return $scope.accounts = data;
          });
        };
        $scope.saveAccount = function(accountId) {
          return accountService.saveAccount(accountId, function(data) {
            notify.success("Successfully saved account with id: " + accountId);
            return $scope.refreshAccounts();
          });
        };
        $scope.deleteAccount = function(accountId) {
          return accountService.deleteAccount(accountId, function(data) {
            notify.success("Successfully deleted account with id: " + accountId);
            return $scope.refreshAccounts();
          });
        };
        $scope.refreshMachines = function(accountId) {
          return machineService.getMachines(accountId, function(data) {
            return $scope.accountMachines = data;
          });
        };
        $scope.saveMachine = function(accountId, uuid) {
          return machineService.saveMachine(accountId, uuid, function(data) {
            notify.success("Successfully saved machine with uuid: " + uuid + " to account: " + accountId);
            return $scope.refreshMachines(accountId);
          });
        };
        $scope.deleteMachine = function(accountId, uuid) {
          return machineService.deleteMachine(accountId, uuid, function(data) {
            notify.success("Successfully deleted machine with id: " + uuid + " from account: " + accountId);
            return $scope.refreshMachines(accountId);
          });
        };
        $scope.refreshAccounts();
        $scope.$apply();
      }
    ];
  });

}).call(this);
